export const Colors = {
  light: {
    'surface': '#f8f9ff',
    'surface-dim': '#cbdbf5',
    'surface-bright': '#f8f9ff',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#e5eeff',
    'surface-container': '#dce9ff',
    'surface-container-high': '#d3e4fe',
    'surface-container-highest': '#cbdbf5',
    'on-surface': '#0b1c30',
    'on-surface-variant': '#464555',
    'inverse-surface': '#213145',
    'inverse-on-surface': '#eaf1ff',
    'outline': '#777587',
    'outline-variant': '#c7c4d8',
    'surface-tint': '#3525cd',
    'primary': '#3525cd',
    'on-primary': '#fef5f5',
    'primary-container': '#4f46e5',
    'on-primary-container': '#dad7ff',
    'inverse-primary': '#c3c0ff',
    'secondary': '#4648d4',
    'on-secondary': '#fef5f5',
    'secondary-container': '#6063ee',
    'on-secondary-container': '#fffbff',
    'tertiary': '#005338',
    'on-tertiary': '#fef5f5',
    'tertiary-container': '#006e4b',
    'on-tertiary-container': '#67f4b7',
    'error': '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#e2dfff',
    'primary-fixed-dim': '#c3c0ff',
    'on-primary-fixed': '#0f0069',
    'on-primary-fixed-variant': '#3323cc',
    'secondary-fixed': '#e1e0ff',
    'secondary-fixed-dim': '#c0c1ff',
    'on-secondary-fixed': '#07006c',
    'on-secondary-fixed-variant': '#2f2ebe',
    'tertiary-fixed': '#6ffbbe',
    'tertiary-fixed-dim': '#4edea3',
    'on-tertiary-fixed': '#002113',
    'on-tertiary-fixed-variant': '#005236',
    'background': '#f8f9ff',
    'on-background': '#0b1c30',
    'surface-variant': '#d3e4fe',
  },
  dark: {
    'surface': '#031427',
    'surface-dim': '#031427',
    'surface-bright': '#2a3a4f',
    'surface-container-lowest': '#0b1c30',
    'surface-container-low': '#102034',
    'surface-container': '#1b2b3f',
    'surface-container-high': '#26364a',
    'surface-container-highest': '#2a3a4f',
    'on-surface': '#d3e4fe',
    'on-surface-variant': '#c7c4d8',
    'inverse-surface': '#d3e4fe',
    'inverse-on-surface': '#213145',
    'outline': '#918fa1',
    'outline-variant': '#464555',
    'surface-tint': '#c3c0ff',
    'primary': '#c3c0ff',
    'on-primary': '#1d00a5',
    'primary-container': '#4f46e5',
    'on-primary-container': '#dad7ff',
    'inverse-primary': '#3525cd',
    'secondary': '#c0c1ff',
    'on-secondary': '#1000a9',
    'secondary-container': '#3131c0',
    'on-secondary-container': '#b0b2ff',
    'tertiary': '#4edea3',
    'on-tertiary': '#003824',
    'tertiary-container': '#006e4b',
    'on-tertiary-container': '#67f4b7',
    'error': '#ffb4ab',
    'on-error': '#690005',
    'error-container': '#93000a',
    'on-error-container': '#ffdad6',
    'primary-fixed': '#e2dfff',
    'primary-fixed-dim': '#c3c0ff',
    'on-primary-fixed': '#0f0069',
    'on-primary-fixed-variant': '#3323cc',
    'secondary-fixed': '#e1e0ff',
    'secondary-fixed-dim': '#c0c1ff',
    'on-secondary-fixed': '#07006c',
    'on-secondary-fixed-variant': '#2f2ebe',
    'tertiary-fixed': '#6ffbbe',
    'tertiary-fixed-dim': '#4edea3',
    'on-tertiary-fixed': '#002113',
    'on-tertiary-fixed-variant': '#005236',
    'background': '#031427',
    'on-background': '#d3e4fe',
    'surface-variant': '#26364a',
  },
} as const;

export type ColorScheme = keyof typeof Colors;
export type ThemeColors = (typeof Colors)[ColorScheme];

// Section 5 — Typography
// Font sizes from the design system. Each scale also maps to a Poppins weight.
export const FontFamily = {
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  semibold: 'Poppins-SemiBold',
  bold: 'Poppins-Bold',
} as const;

export const Typography = {
  display: { fontFamily: FontFamily.bold, fontSize: 40 },
  hero: { fontFamily: FontFamily.semibold, fontSize: 28 },
  hero2: { fontFamily: FontFamily.bold, fontSize: 28 },
  title: { fontFamily: FontFamily.semibold, fontSize: 21 },
  screenTitle: { fontFamily: FontFamily.semibold, fontSize: 15 },
  body: { fontFamily: FontFamily.regular, fontSize: 13 },
  caption: { fontFamily: FontFamily.regular, fontSize: 11 },
  micro: { fontFamily: FontFamily.regular, fontSize: 10 },
  button: { fontFamily: FontFamily.medium, fontSize: 16 },
} as const;

export type TypographyVariant = keyof typeof Typography;

// Section 6 — Grid System
export const Grid = {
  columns: {
    count: 4,
    margin: 20,
    gutter: 16,
  },
} as const;
